openapi: 3.2.0
info:
  title: Operator Management Data Bridge API
  description: A RESTful API that allows users to manage Big Peer apps and API keys.
  license:
    name: Ditto Binary License
    identifier: Ditto Binary License
  version: 1.0.0
servers:
- url: http://localhost:{port}
  description: Local server
  variables:
    port:
      default: '8080'
tags:
- name: Data Bridge
  description: Apps' data bridges (CDC)
paths:
  /namespace/{namespace}/bigPeer/{big_peer_name}/app/{app_name}/dataBridge:
    get:
      tags:
      - Data Bridge
      summary: List Data Bridges
      description: Lists all data bridges (CDC or MongoDB Connector) associated with a Big Peer app.
      operationId: listDataBridges
      responses:
        '200':
          description: List of data bridges for the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse_DataBridgeObject'
        '404':
          description: App not found
          content:
            application/json:
              examples:
                AppNotFound:
                  summary: app not found
    post:
      tags:
      - Data Bridge
      summary: Create Data Bridge
      description: Creates a new data bridge for CDC or MongoDB Connector integration.
      operationId: createDataBridge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataBridgeRequest'
        required: true
      responses:
        '201':
          description: Data bridge successfully created for app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataBridgeObject'
        '400':
          description: Bad request
          content:
            application/json:
              examples:
                WebhookNotSupported:
                  summary: webhook destinations are not supported
        '404':
          description: App not found
          content:
            application/json:
              examples:
                AppNotFound:
                  summary: app not found
  /namespace/{namespace}/bigPeer/{big_peer_name}/app/{app_name}/dataBridge/{data_bridge_name}:
    get:
      tags:
      - Data Bridge
      summary: Get Data Bridge
      description: Retrieves details for a specific data bridge.
      operationId: getDataBridge
      responses:
        '200':
          description: Data bridge details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataBridgeObject'
        '404':
          description: App or data bridge not found
          content:
            application/json:
              examples:
                AppNotFound:
                  summary: app not found
                DataBridgeNotFound:
                  summary: data bridge not found
    delete:
      tags:
      - Data Bridge
      summary: Delete Data Bridge
      description: Deletes a data bridge.
      operationId: deleteDataBridge
      responses:
        '204':
          description: Data bridge successfully deleted
          content:
            application/json:
              schema:
                default: null
        '404':
          description: App or data bridge not found
          content:
            application/json:
              examples:
                AppNotFound:
                  summary: app not found
                DataBridgeNotFound:
                  summary: data bridge not found
